name: CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Debug

      - name: Run tests
        run: dotnet test --no-build --configuration Debug
      
      - name: Checkout Allure history
        uses: actions/checkout@v4
        if: always()  # Always run this step, even if previous steps fail
        continue-on-error: true  # Continue even if this step fails
        with:
          ref: gh-pages  # Checkout the gh-pages branch for Allure reports
          path: gh-pages  # Specify the path to checkout to

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()  # Always run this step, even if previous steps fail
        with:
          allure_history: gh-pages/allure-history  # Path to the history directory in the checked-out gh-pages branch
          allure_results: src/allure-results  # Path to the test results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()  # Always run this step, even if previous steps fail
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
          publish_branch: gh-pages  # Specify the branch to publish to
          publish_dir: allure-history  # Directory containing the report to publish